# This is a sample manifest for utilizing the topology feature
# PVCs created using this storage class will be scheduled 
# only on the nodes with ISCSI access to the PowerMax

# Change all instances to <SYMID> to the Symmetrix ID of the PowerMax array
# In case you installed the driver with a custom name, then replace all instances of 
# "csi-powermax.dellemc.com" with the custom provisioner name

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: powermax-iscsi
parameters:
  SRP: <SRP Name> #Insert SRP name here
  SYMID: <SYMID> #Insert Symmetrix ID
  ServiceLevel: <Service Level> #Insert Service Level Name
provisioner: csi-powermax.dellemc.com 
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
allowedTopologies:
- matchLabelExpressions:
  - key: csi-powermax.dellemc.com/<SYMID>
    values:
    - csi-powermax.dellemc.com
  - key: csi-powermax.dellemc.com/<SYMID>.iscsi
    values:
    - csi-powermax.dellemc.com
